version: '3.8'
services:
  database:
    image: postgres:latest
    container_name: database_container
    volumes:
      - database:/database
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    networks:
      - matcha

  backend:
    build: ./backend
    # environment:
    volumes:
      - backend:/opt/backend/
    depends_on:
      - database
    ports:
      - "3000:3000"
    networks:
      - matcha

  frontend:
    build: ./frontend
    volumes:
      - frontend:/opt/frontend/
    # environment:
    depends_on:
      - backend
    ports:
      - "5173:5173"
    networks:
      - matcha


volumes:
  frontend:
    driver: local
    driver_opts:
      device: ./frontend
      type: none
      o: bind
  backend:
    driver: local
    driver_opts:
      device: ./backend
      type: none
      o: bind
  database:
    driver: local
    driver_opts:
      device: ./database
      type: none
      o: bind
networks:
  matcha:
